### PR TITLE
A few tweaks to allow further customizations

### PR DESCRIPTION
**Pull request by nogweii**
I'd like to change some of the choices, but wasn't able to since they are hard-coded. Adding additional variables fixes that.

### CODE REVIEW

**Comment by bodsch** [comment]
Thank you for your PR!
I will have a look at it at my leisure.

**Comment by bodsch** [comment]
What kind of choices are we talking about?

As far as I can see, the changes to `k0s_delegate_to`, `k0s_local_tmp_directory` are not necessary, or I don't understand the meaning behind your changes.

**Comment by nogweii** [comment]
Sure! Most of the changes are about allowing me as a consumer of the k0s role to be able to tweak more of the settings.

* `k0s_delegate_to` is moved from `vars/main.yml` to `defaults/main.yml` in order to make it easier to override. It being within vars/ means it's really deep in the [Ansible variable precendence](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence). If I wanted to override the value, I'd have to specify just that particular variable when using `import_role` or specifying the role in a playbook. I could not override it's value in a variable from my inventory, or by specifying it globally in a playbook's `vars:` section. It has a static default, and does not depend on another value, so moving it to `defaults/` makes it easier to override without impacting functionality.
* `k0s_local_tmp_directory` is changed to allow overriding the location using an Ansible variable (`k0s_controller_download_dir` from defaults) rather than only via environment variables. This is a personal preference: I'd like to configure the roles I'm using entirely within Ansible, without relying on certain external state being set.

All of these commits are in service of allowing downstream users of the role to be able to configure the values without requiring them to track edits to the role.

**Comment by bodsch** [comment]
Perhaps you are misinterpreting my way of using these variables ... let me explain briefly.

**`k0s_delegate_to` is not intended to be overwritten.**

By default, this variable points to `localhost`, i.e. to the Ansible controller.
I integrated this to enable the download of the archive on the controller, which then transfers the archive to the target systems.
In my work environment, not every instance has access to the internet or GitHub.
If this form of downloading is not desired, `k0s_direct_download` can be set to `true`.
In this case, the archive is downloaded from GitHub by each instance.

If `k0s_direct_download` is **not** set to `true` - i.e. the Ansible controller does the downloading - `k0s_local_tmp_directory` is set to `$HOME/.cache/ansible/k0s/$k0s_main_version`.
If `k0s_direct_download` has been overwritten with `true`, `k0s_local_tmp_directory` == `/var/cache/ansible/k0s/$k0s_main_version`.
If this is not wanted, an environment variable `CUSTOM_LOCAL_TMP_DIRECTORY` can be defined.

This is it.
This works excellently in all environments in which I use this role.

**Comment by bodsch** [comment]
@nogweii ping

**Comment by bodsch** [comment]
stale

**Comment by bodsch** [comment]
No feedback.

As there was no real improvement for me, the PR will be closed.

**Pull request closed without merging**
